# Generated by Django 2.0.1 on 2018-01-20 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0003_auto_20180115_0844'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid')], default='NOT_PAID', max_length=8)),
                ('additional_notes', models.TextField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
