# Generated by Django 2.0.1 on 2018-01-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180120_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
