# Generated by Django 2.0.1 on 2018-01-25 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20180120_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.Bill'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
